#!/usr/bin/env bash

PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "$*" >&2; exit 1; }


res=$(grp 1234) || die

# Note: assumes defaults of -c 3 and -s ' ':
[[ $res == '1 234' ]]

