#!/usr/bin/env bash

PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "$*" >&2; exit 1; }

# Note: assumes defaults of -c 3 and -s ' ':

res=$(grp -l <<<1234)
[[ $res == '123 4' ]] || die "stdin, single arg"

res=$(LC_ALL='en_US.UTF-8' grp -n <<<1234)
[[ $res == '1,234' ]] || die "-n: stdin, single arg"

res=$(grp -l <<<$'1234\n4567')
[[ $res == $'123 4\n456 7' ]] || die "stdin, multiple args"

res=$(LC_ALL='en_US.UTF-8' grp -n <<<$'1234\n4567')
[[ $res == $'1,234\n4,567' ]] || die "-n: stdin, multiple args"

res=$(grp -l 1234)
[[ $res == '123 4' ]] || die "operand, single"

res=$(LC_ALL='en_US.UTF-8' grp -n 1234)
[[ $res == '1,234' ]] || die "-n: operand, single"

res=$(grp -l 1234 4567)
[[ $res == $'123 4\n456 7' ]] || die "operand, multiple"

res=$(LC_ALL='en_US.UTF-8' grp -n 1234 4567)
[[ $res == $'1,234\n4,567' ]] || die "-n: operand, multiple"

exit 0
